name: Build CYFS Gateway for MacOS
on: 
    workflow_call:
        inputs:
            arch:
                required: true
                type: string
            enable_tests:
                required: false
                type: boolean
                default: false

jobs:
  build:
    name: build
    runs-on: ${{ inputs.arch == 'aarch64' && 'macos-15' || 'macos-15-intel' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: "latest"
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: ${{inputs.arch}}-apple-darwin
    - name: cargo test
      working-directory: ./src
      if: ${{inputs.enable_tests == 'true'}}
      run: sudo cargo test -- --test-threads=1
    - name: install buckyos devkit
      run: pip install "buckyos-devkit @ git+https://github.com/buckyos/buckyos-devkit.git"
    - name: build buckyos
      working-directory: ./src
      run: sudo buckyos-build --app=cyfs-gateway-publish
    - name: Tar Rootfs
      run: 
        cd ./src/rootfs && tar -czvf ../../gateway-apple-${{inputs.arch == 'x86_64' && 'amd64' || 'aarch64'}}.tar.gz .
    - name: Upload
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: gateway-apple-${{inputs.arch == 'x86_64' && 'amd64' || 'aarch64'}}
        path: gateway-apple-${{inputs.arch == 'x86_64' && 'amd64' || 'aarch64'}}.tar.gz
        if-no-files-found: error
